package com.bitsapplied.descartes.tools.threadanalyzer;

import com.bitsapplied.descartes.tools.threadanalyzer.strategies.ThreadDumpStrategy;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Builds thread dumps incrementally with real-time size tracking and truncation.
 *
 * <p>This builder:
 * <ul>
 *   <li>Tracks UTF-8 byte size in real-time</li>
 *   <li>Enforces size limits by stopping generation when budget exhausted</li>
 *   <li>Records detailed metadata about what was included/excluded</li>
 *   <li>Provides truncation footer with helpful information</li>
 * </ul>
 *
 * @since 0.0.1
 */
public class ThreadDumpBuilder {

    private final StringBuilder dump;
    private final DetailLevelController detailController;
    private final ThreadDumpStrategy strategy;
    private final int maxStackDepth;
    private final String filterStackPattern;

    private int threadsIncluded;
    private int threadsExcluded;
    private int threadsSkippedDueToSize;
    private int threadsSkippedDueToScore;
    private boolean truncated;
    private final List<ThreadSummary> includedThreads;
    private final Map<String, Integer> exclusionBreakdown;

    /**
     * Creates a builder with the specified configuration.
     *
     * @param detailController Controller for managing detail levels
     * @param strategy Strategy being used
     * @param maxStackDepth Maximum stack depth
     * @param filterStackPattern Optional stack frame filter pattern
     */
    public ThreadDumpBuilder(DetailLevelController detailController, ThreadDumpStrategy strategy,
                             int maxStackDepth, String filterStackPattern) {
        this.dump = new StringBuilder();
        this.detailController = detailController;
        this.strategy = strategy;
        this.maxStackDepth = maxStackDepth;
        this.filterStackPattern = filterStackPattern;

        this.threadsIncluded = 0;
        this.threadsExcluded = 0;
        this.threadsSkippedDueToSize = 0;
        this.threadsSkippedDueToScore = 0;
        this.truncated = false;
        this.includedThreads = new ArrayList<>();
        this.exclusionBreakdown = new HashMap<>();

        // Add header
        addHeader();
    }

    /**
     * Adds the dump header.
     */
    private void addHeader() {
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss"));
        String header = String.format("Full thread dump (Generated by Descartes MCP - %s):\n\n", timestamp);
        dump.append(header);
        recordBytes(header);
    }

    /**
     * Attempts to add a thread to the dump.
     *
     * @param pair Thread-score pair
     * @param threadFormatter Function to format the thread
     * @return true if thread was added, false if skipped due to size
     */
    public boolean tryAddThread(ThreadDumpStrategy.ThreadScorePair pair,
                                 ThreadFormatter threadFormatter) {
        // Get current detail level
        DetailLevelController.DetailLevel detailLevel = detailController.getCurrentDetailLevel();

        // Format thread with current detail level
        String threadSection = formatThreadSection(pair, detailLevel, threadFormatter);

        // Measure size
        int sectionSize = measureUtf8Size(threadSection);

        // Check if we have room
        if (!detailController.hasRoom(sectionSize)) {
            // Try with reduced detail level
            if (detailLevel != DetailLevelController.DetailLevel.SUMMARY) {
                detailController.recordDetailReduction();
                // Retry with next lower detail level will happen on next iteration
            }

            threadsSkippedDueToSize++;
            threadsExcluded++;
            truncated = true;
            return false;
        }

        // Add to dump
        dump.append(threadSection);
        recordBytes(threadSection);
        threadsIncluded++;

        // Record in included threads summary
        includedThreads.add(new ThreadSummary(
            pair.threadInfo().getThreadName(),
            pair.threadInfo().getThreadId(),
            pair.threadInfo().getThreadState().name(),
            pair.score(),
            pair.cpuTimeMs(),
            pair.threadInfo().getBlockedTime()
        ));

        return true;
    }

    /**
     * Formats a thread section based on detail level.
     */
    private String formatThreadSection(ThreadDumpStrategy.ThreadScorePair pair,
                                       DetailLevelController.DetailLevel detailLevel,
                                       ThreadFormatter threadFormatter) {
        int adjustedStackDepth = detailLevel.getStackDepth(maxStackDepth);

        if (detailLevel == DetailLevelController.DetailLevel.SUMMARY) {
            // Summary only: name, state, CPU time
            return String.format("\"%s\" #%d state=%s cpu=%dms\n\n",
                pair.threadInfo().getThreadName(),
                pair.threadInfo().getThreadId(),
                pair.threadInfo().getThreadState(),
                pair.cpuTimeMs());
        }

        // Use the provided formatter (delegates to AbstractThreadOperation.formatThreadInfo)
        return threadFormatter.format(pair.threadInfo(), adjustedStackDepth, filterStackPattern) + "\n";
    }

    /**
     * Records that threads were excluded due to low score.
     *
     * @param count Number of threads excluded
     */
    public void recordThreadsExcludedByScore(int count) {
        threadsSkippedDueToScore = count;
        threadsExcluded += count;
    }

    /**
     * Adds truncation footer with helpful information.
     */
    public void addTruncationFooter() {
        if (!truncated) {
            return;
        }

        StringBuilder footer = new StringBuilder();
        footer.append("\n");
        footer.append("=".repeat(70)).append("\n");
        footer.append("=== DUMP TRUNCATED DUE TO SIZE LIMIT ===\n");
        footer.append("=".repeat(70)).append("\n");
        footer.append(String.format("Threads included: %d\n", threadsIncluded));
        footer.append(String.format("Threads omitted: %d\n", threadsExcluded));

        if (threadsSkippedDueToSize > 0) {
            footer.append(String.format("  - Due to size limit: %d\n", threadsSkippedDueToSize));
        }
        if (threadsSkippedDueToScore > 0) {
            footer.append(String.format("  - Due to low importance score: %d\n", threadsSkippedDueToScore));
        }

        footer.append(String.format("Size limit: %,d bytes\n", detailController.getTotalBudget()));
        footer.append(String.format("Size used: %,d bytes\n", detailController.getUsedBudget()));

        if (detailController.getDetailReductionCount() > 0) {
            footer.append(String.format("Detail reductions applied: %d\n",
                detailController.getDetailReductionCount()));
        }

        footer.append("\nTo see more threads, try:\n");
        footer.append("  - Apply name_pattern to focus on specific subsystem\n");
        footer.append("  - Use state_filter to show only specific states\n");
        footer.append("  - Reduce max_stack_depth to fit more threads\n");
        footer.append("  - Use thread_search for targeted investigation\n");
        footer.append("  - Use thread_inspect for specific thread IDs\n");
        footer.append("=".repeat(70)).append("\n");

        String footerStr = footer.toString();
        dump.append(footerStr);
        // Don't record footer bytes (it's added after size limit reached)
    }

    /**
     * Records bytes used from the string.
     */
    private void recordBytes(String text) {
        detailController.recordBytesUsed(measureUtf8Size(text));
    }

    /**
     * Measures the UTF-8 byte size of a string.
     */
    private int measureUtf8Size(String text) {
        return text.getBytes(StandardCharsets.UTF_8).length;
    }

    /**
     * Gets the final dump string.
     *
     * @return Thread dump
     */
    public String getDump() {
        return dump.toString();
    }

    /**
     * Checks if dump was truncated.
     *
     * @return true if truncated
     */
    public boolean isTruncated() {
        return truncated;
    }

    /**
     * Gets the number of threads included.
     *
     * @return Threads included count
     */
    public int getThreadsIncluded() {
        return threadsIncluded;
    }

    /**
     * Gets the number of threads excluded.
     *
     * @return Threads excluded count
     */
    public int getThreadsExcluded() {
        return threadsExcluded;
    }

    /**
     * Gets the list of included thread summaries.
     *
     * @return Included threads
     */
    public List<ThreadSummary> getIncludedThreads() {
        return List.copyOf(includedThreads);
    }

    /**
     * Gets the exclusion breakdown.
     *
     * @return Map of exclusion reasons to counts
     */
    public Map<String, Integer> getExclusionBreakdown() {
        Map<String, Integer> breakdown = new HashMap<>();
        if (threadsSkippedDueToScore > 0) {
            breakdown.put("low_importance_score", threadsSkippedDueToScore);
        }
        if (threadsSkippedDueToSize > 0) {
            breakdown.put("size_limit_reached", threadsSkippedDueToSize);
        }
        return breakdown;
    }

    /**
     * Summary of an included thread.
     */
    public record ThreadSummary(String name, long id, String state, int score, long cpuTimeMs, long blockedTimeMs) {}

    /**
     * Functional interface for thread formatting.
     * Allows delegation to AbstractThreadOperation.formatThreadInfo.
     */
    @FunctionalInterface
    public interface ThreadFormatter {
        String format(java.lang.management.ThreadInfo threadInfo, int maxStackDepth, String filterPattern);
    }
}
